### ISSUE TITLE
Upgrading to AGP 8.x breaks Netty somehow

### ISSUE THREAD

**Issue by grote** [onionshare/onionshare-android#107]
Upgrading the Android Gradle Plugin to 8.x (e.g. https://github.com/onionshare/onionshare-android/commit/af97116d87204d0d09a25a599e6dc98059986fed) causes Netty to present some wierdness. At some point it stops to answer requests and logs those exceptions:

``` ruby
i.n.c.Defa...elPipeline org.onionshare.android               W  An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.io.netty.channel.ChannelPipelineException: io.ktor.server.netty.NettyChannelInitializer is not a @Sharable handler, so can't be added or removed multiple times.
                 	at io.netty.channel.DefaultChannelPipeline.checkMultiplicity(DefaultChannelPipeline.java:600)
                 	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:202)
                 	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:381)
                 	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:370)
                 	at io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor.channelRead(ServerBootstrap.java:209)
                 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
                 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
                 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
                 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
                 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
                 	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:97)
                 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
                 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
                 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
                 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
                 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
                 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                 	at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)
                 	at io.ktor.server.netty.EventLoopGroupProxy$Companion.$r8$lambda$XgnKz7L6tCWRUaIAa7SVURwtFE4(NettyApplicationEngine.kt:0)
                 	at io.ktor.server.netty.EventLoopGroupProxy$Companion$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
                 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                 	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by grote** [comment]
Still happening with latest dependencies:

```java
i.n.c.Chan...nitializer  W  Failed to initialize a channel. Closing: [id: 0x56c54309, L:/127.0.0.1:[scrubbed] - R:/127.0.0.1:[scrubbed]]java.lang.IllegalStateException: unknown type parameter 'I': class io.netty.handler.codec.MessageToMessageEncoder
                            	at io.netty.util.internal.TypeParameterMatcher.find0(TypeParameterMatcher.java:92)
                            	at io.netty.util.internal.TypeParameterMatcher.find(TypeParameterMatcher.java:68)
                            	at io.netty.handler.codec.MessageToMessageEncoder.<init>(MessageToMessageEncoder.java:61)
                            	at io.netty.handler.codec.http.HttpObjectEncoder.<init>(HttpObjectEncoder.java:54)
                            	at io.netty.handler.codec.http.HttpResponseEncoder.<init>(HttpResponseEncoder.java:27)
                            	at io.netty.handler.codec.http.HttpServerCodec$HttpServerResponseEncoder.<init>(HttpServerCodec.java:178)
                            	at io.netty.handler.codec.http.HttpServerCodec$HttpServerResponseEncoder.<init>(HttpServerCodec.java:178)
                            	at io.netty.handler.codec.http.HttpServerCodec.<init>(HttpServerCodec.java:147)
                            	at io.netty.handler.codec.http.HttpServerCodec.<init>(HttpServerCodec.java:68)
                            	at io.ktor.server.netty.NettyApplicationEngine$Configuration.defaultHttpServerCodec(NettyApplicationEngine.kt:106)
                            	at io.ktor.server.netty.NettyApplicationEngine$Configuration.access$defaultHttpServerCodec(NettyApplicationEngine.kt:38)
                            	at io.ktor.server.netty.NettyApplicationEngine$Configuration$httpServerCodec$1.invoke(NettyApplicationEngine.kt:96)
                            	at io.ktor.server.netty.NettyApplicationEngine$Configuration$httpServerCodec$1.invoke(NettyApplicationEngine.kt:96)
                            	at io.ktor.server.netty.NettyChannelInitializer.configurePipeline(NettyChannelInitializer.kt:138)
                            	at io.ktor.server.netty.NettyChannelInitializer.initChannel(NettyChannelInitializer.kt:101)
                            	at io.ktor.server.netty.NettyChannelInitializer.initChannel(NettyChannelInitializer.kt:29)
                            	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
                            	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
                            	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1130)
                            	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:608)
                            	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:45)
                            	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1460)
                            	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1114)
                            	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:649)
                            	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:513)
                            	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:428)
                            	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:485)
                            	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
                            	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
                            	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
                            	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
                            	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
                            	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                            	at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)
                            	at io.ktor.server.netty.EventLoopGroupProxy$Companion.$r8$lambda$-W8F1fLR_nY9jIqnQW-3VF2-Vsc(NettyApplicationEngine.kt:0)
                            	at io.ktor.server.netty.EventLoopGroupProxy$Companion$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
                            	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                            	at java.lang.Thread.run(Thread.java:1117)
i.n.c.Defa...elPipeline  W  An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.io.netty.channel.ChannelPipelineException: io.ktor.server.netty.NettyChannelInitializer is not a @Sharable handler, so can't be added or removed multiple times.
                            	at io.netty.channel.DefaultChannelPipeline.checkMultiplicity(DefaultChannelPipeline.java:599)
                            	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:201)
                            	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:380)
                            	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:369)
                            	at io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor.channelRead(ServerBootstrap.java:225)
                            	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
                            	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                            	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
                            	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407)
                            	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
                            	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
                            	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
                            	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:97)
                            	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
                            	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
                            	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
                            	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
                            	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
                            	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                            	at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)
                            	at io.ktor.server.netty.EventLoopGroupProxy$Companion.$r8$lambda$-W8F1fLR_nY9jIqnQW-3VF2-Vsc(NettyApplicationEngine.kt:0)
                            	at io.ktor.server.netty.EventLoopGroupProxy$Companion$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
                            	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                            	at java.lang.Thread.run(Thread.java:1117)
```

**Comment by grote** [comment]
Good news: It is working if I add the following proguard rules:

```proguard
-keep class io.netty.** { *; }

-dontwarn com.aayushatharva.brotli4j.**
-dontwarn com.github.luben.zstd.**
-dontwarn com.google.protobuf.**
-dontwarn com.jcraft.jzlib.**
-dontwarn com.ning.compress.**
-dontwarn com.oracle.svm.core.annotate.**
-dontwarn lzma.sdk.**
-dontwarn net.jpountz.lz4.**
-dontwarn net.jpountz.xxhash.**
-dontwarn org.jboss.marshalling.**
-dontwarn org.osgi.annotation.**
-dontwarn reactor.blockhound.**
-dontwarn sun.security.x509.**
```

would be nice to figure out exactly what is causing the issue though.
