### ISSUE TITLE
SecurityException: openInputStream() in FileManager#zipFiles()

### ISSUE THREAD

**Issue by grote** [onionshare/onionshare-android#15]
Samsung Galaxy A71 Android 10 (SDK 29)

```ruby
java.lang.SecurityException: 
  at android.os.Parcel.createException (Parcel.java:2088)
  at android.os.Parcel.readException (Parcel.java:2056)
  at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:188)
  at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel (DatabaseUtils.java:151)
  at android.content.ContentProviderProxy.openTypedAssetFile (ContentProviderNative.java:705)
  at android.content.ContentResolver.openTypedAssetFileDescriptor (ContentResolver.java:1694)
  at android.content.ContentResolver.openAssetFileDescriptor (ContentResolver.java:1510)
  at android.content.ContentResolver.openInputStream (ContentResolver.java:1194)
  at org.onionshare.android.files.FileManager.zipFiles (FileManager.kt:70)
  at org.onionshare.android.ShareManager.getSendPage (ShareManager.kt:118)
  at org.onionshare.android.ShareManager.access$getSendPage (ShareManager.kt:32)
  at org.onionshare.android.ShareManager$startSharing$2.invokeSuspend (ShareManager.kt:94)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.kt:571)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.kt:750)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:678)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:665)
```

Potentially related to https://code.briarproject.org/briar/briar/-/issues/2143 or https://code.briarproject.org/briar/briar/-/issues/2216

**Comment by grote** [comment]
Slightly different trace from Samsung Galaxy S10e Android 11 (SDK 30)


```ruby
java.lang.SecurityException: 
  at android.os.Parcel.createExceptionOrNull (Parcel.java:2385)
  at android.os.Parcel.createException (Parcel.java:2369)
  at android.os.Parcel.readException (Parcel.java:2352)
  at android.os.Parcel.readException (Parcel.java:2294)
  at android.app.IActivityManager$Stub$Proxy.getContentProvider (IActivityManager.java:6701)
  at android.app.ActivityThread.acquireProvider (ActivityThread.java:7764)
  at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider (ContextImpl.java:3090)
  at android.content.ContentResolver.acquireUnstableProvider (ContentResolver.java:2491)
  at android.content.ContentResolver.openTypedAssetFileDescriptor (ContentResolver.java:1977)
  at android.content.ContentResolver.openAssetFileDescriptor (ContentResolver.java:1808)
  at android.content.ContentResolver.openInputStream (ContentResolver.java:1485)
  at org.onionshare.android.files.FileManager.zipFiles (FileManager.kt:70)
  at org.onionshare.android.ShareManager.getSendPage (ShareManager.kt:118)
  at org.onionshare.android.ShareManager.access$getSendPage (ShareManager.kt:32)
  at org.onionshare.android.ShareManager$startSharing$2.invokeSuspend (ShareManager.kt:94)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.kt:571)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.kt:750)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:678)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:665)
```

**Comment by grote** [comment]
Also happened with a non-Samsung phone: **Redmi Note 9S** Android 11 (SDK 30)

```ruby
java.lang.SecurityException: 
  at android.os.Parcel.createExceptionOrNull (Parcel.java:2376)
  at android.os.Parcel.createException (Parcel.java:2360)
  at android.os.Parcel.readException (Parcel.java:2343)
  at android.os.Parcel.readException (Parcel.java:2285)
  at android.app.IActivityManager$Stub$Proxy.getContentProvider (IActivityManager.java:5949)
  at android.app.ActivityThread.acquireProvider (ActivityThread.java:6999)
  at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider (ContextImpl.java:2954)
  at android.content.ContentResolver.acquireUnstableProvider (ContentResolver.java:2509)
  at android.content.ContentResolver.openTypedAssetFileDescriptor (ContentResolver.java:1994)
  at android.content.ContentResolver.openAssetFileDescriptor (ContentResolver.java:1825)
  at android.content.ContentResolver.openInputStream (ContentResolver.java:1502)
  at org.onionshare.android.files.FileManager.zipFiles (FileManager.kt:70)
  at org.onionshare.android.ShareManager.getSendPage (ShareManager.kt:118)
  at org.onionshare.android.ShareManager.access$getSendPage (ShareManager.kt:32)
  at org.onionshare.android.ShareManager$startSharing$2.invokeSuspend (ShareManager.kt:94)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.kt:571)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.kt:750)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:678)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:665)
```

**Comment by grote** [comment]
Samsung Galaxy J6+ Android 10 (SDK 29)

```ruby
java.lang.SecurityException: 
  at android.os.Parcel.createException (Parcel.java:2088)
  at android.os.Parcel.readException (Parcel.java:2056)
  at android.os.Parcel.readException (Parcel.java:2004)
  at android.app.IActivityManager$Stub$Proxy.getContentProvider (IActivityManager.java:5776)
  at android.app.ActivityThread.acquireProvider (ActivityThread.java:7123)
  at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider (ContextImpl.java:2893)
  at android.content.ContentResolver.acquireUnstableProvider (ContentResolver.java:2124)
  at android.content.ContentResolver.openTypedAssetFileDescriptor (ContentResolver.java:1678)
  at android.content.ContentResolver.openAssetFileDescriptor (ContentResolver.java:1510)
  at android.content.ContentResolver.openInputStream (ContentResolver.java:1194)
  at org.onionshare.android.files.FileManager.zipFiles (FileManager.kt:70)
  at org.onionshare.android.ShareManager.getSendPage (ShareManager.kt:118)
  at org.onionshare.android.ShareManager.access$getSendPage (ShareManager.kt:32)
  at org.onionshare.android.ShareManager$startSharing$2.invokeSuspend (ShareManager.kt:94)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.kt:571)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.kt:750)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:678)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:665)
Caused by: android.os.RemoteException: 
  at com.android.server.am.ActivityManagerService.getContentProviderImpl (ActivityManagerService.java:8308)
  at com.android.server.am.ActivityManagerService.getContentProviderImpl (ActivityManagerService.java:8154)
  at com.android.server.am.ActivityManagerService.getContentProvider (ActivityManagerService.java:8784)
  at android.app.IActivityManager$Stub.onTransact (IActivityManager.java:2417)
  at com.android.server.am.ActivityManagerService.onTransact (ActivityManagerService.java:3359)
```

**Comment by akwizgran** [comment]
The process getting restarted sounds plausible - in Briar we had issues with the UI being hidden due to low memory when the user was picking a photo from the gallery, and since OnionShare isn't running a foreground service at this point it might be killed under the same low memory conditions. So if the user picked one file, then went back to the gallery to pick another and OnionShare's process was killed and restarted, I guess the permission to use the first file might be lost?

Perhaps using the developer option to destroy activities would help to reproduce this, if the permission is tied to the activity or view model rather than the process?

I don't have any of the phones listed above but I have a couple of Samsung phones that I can use to try to reproduce this.

**Comment by grote** [comment]
I tried reproducing the process/activity killing, but then the ViewModel and its state also gets killed, so when the user navigates back they don't have the option anymore to start sharing.

In #21 I tried to just use that `FLAG_GRANT_READ_URI_PERMISSION` with the option to also take persistent permissions on the Uri. I'd let our testers test it without the persistent permission first and if the crash still gets reported, activate that persistent permission taking. If the crash doesn't happen anymore, I'd revert that commit and just add the intent FLAG back.

**Comment by akwizgran** [comment]
I can reproduce this on the Samsung Galaxy A10s using #21:

* Select a file, start sharing
* Back out of the activity - the activity and view model are destroyed but the foreground service is still running
* Relaunch the app from the launcher icon
* Stop sharing
* Start sharing again

```
2022-02-03 13:16:30.376 30833-30883/org.onionshare.android.nightly E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
    Process: org.onionshare.android.nightly, PID: 30833
    java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{4148957 30833:org.onionshare.android.nightly/u0a5} (pid=30833, uid=10005) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)
        at android.os.Parcel.createException(Parcel.java:2369)
        at android.os.Parcel.readException(Parcel.java:2352)
        at android.os.Parcel.readException(Parcel.java:2294)
        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6683)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:7784)
        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3090)
        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2491)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1977)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1808)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:1485)
        at org.onionshare.android.files.FileManager$zipFiles$2.invokeSuspend(FileManager.kt:71)
        at org.onionshare.android.files.FileManager$zipFiles$2.invoke(Unknown Source:8)
        at org.onionshare.android.files.FileManager$zipFiles$2.invoke(Unknown Source:4)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:212)
        at org.onionshare.android.ShareManager$startSharing$2.invokeSuspend(ShareManager.kt:209)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:9027)
        at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:8866)
        at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:9567)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2843)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3628)
```

**Comment by akwizgran** [comment]
I'll try enabling the persistent permission grant and see if it fixes the issue.

**Comment by akwizgran** [comment]
Didn't help, unfortunately.

**Comment by akwizgran** [comment]
> Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{4148957 30833:org.onionshare.android.nightly/u0a5} (pid=30833, uid=10005) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs

Perhaps the fact that we used ACTION_OPEN_DOCUMENT to get the URI is lost when the activity/view model is destroyed?

**Comment by grote** [comment]
Got it even on a Pixel with plain AOSP. Thanks for your help here! Looking for a fix now.

**Comment by grote** [comment]
> Oh wow, that's unexpected. The persistent permissions are supposed to help with exactly this.

The reason why the persistent permissions don't work is because when pressing 'Start sharing' again, the Tor process gets started which apparently creates an instance of `OnionShareApp` and calls `onCreate()` there which is releasing the persistent permissions again as a way to clean up old ones.

**Comment by akwizgran** [comment]
Ah, nice catch! I hadn't thought about the Tor process having its own Application instance, but come to think of it that's what we used to see with Briar's ACRA process too.

**Comment by akwizgran** [comment]
FIxed by #21.

**Comment by akwizgran** [comment]
I managed to reproduce this again while testing #27 on the Samsung A10s:
* Take a photo
* Open OnionShare, add the photo to the list of shared files
* Switch to the Gallery app, delete the photo ("move to recycle bin")
* Switch back to OnionShare, start sharing

```
2022-02-04 11:39:42.855 15932-16766/org.onionshare.android.nightly E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: org.onionshare.android.nightly, PID: 15932
    java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{b8c33ab 15932:org.onionshare.android.nightly/u0a5} (pid=15932, uid=10005) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)
        at android.os.Parcel.createException(Parcel.java:2369)
        at android.os.Parcel.readException(Parcel.java:2352)
        at android.os.Parcel.readException(Parcel.java:2294)
        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6683)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:7784)
        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3090)
        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2491)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1977)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1808)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:1485)
        at org.onionshare.android.files.FileManager$zipFiles$2.invokeSuspend(FileManager.kt:74)
        at org.onionshare.android.files.FileManager$zipFiles$2.invoke(Unknown Source:8)
        at org.onionshare.android.files.FileManager$zipFiles$2.invoke(Unknown Source:4)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:212)
        at org.onionshare.android.ShareManager$startSharing$2.invokeSuspend(ShareManager.kt:222)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:9027)
        at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:8866)
        at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:9567)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2843)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3628)
```

I'll try reproducing this on another phone to see if Samsung's "recycle bin" is relevant.

**Comment by akwizgran** [comment]
On the Samsung A10s, deleting the file (via OI File Manager from F-Droid) causes the same crash.

The Nokia 1.3 has a Google file manager which "moves files to the bin" rather than deleting them. If a file has already been added to OnionShare's list then moving it to the bin doesn't prevent it from being shared and there's no crash (unlike the A10s). (Moving a file to the bin seems to involve renaming it with the prefix `.trashed-<timestamp>-`.) However, actually deleting the file via OI File Manager results in the same crash as the A10s.

I suggest we catch SecurityException in the same place as FileNotFoundException and treat it in the same way.

**Comment by grote** [comment]
That sounds like a different issue, but unfortunately with the same stack trace. Unfortunately, I can reproduce this on the Pixel as well. I would have hoped this also throws FileNotFoundException, but it doesn't.

> I suggest we catch SecurityException in the same place as FileNotFoundException and treat it in the same way.

Yeah, that's the only solution that comes to my mind as well.
