### ISSUE TITLE
Occasional crash when repeatedly tapping share button

### ISSUE THREAD

**Issue by akwizgran** [onionshare/onionshare-android#48]
I can occasionally trigger a crash by repeatedly tapping the share button (after selecting a file). When the state is "Ready", the button reacts immediately and changes the state to "Starting", but when the state is "Starting" there's a delay in reacting to the button. Repeatedly tapping the button, with long or short pauses between taps, can lead to some strange behaviour, which occasionally includes crashes.

I suspect that multiple start and/or stop tasks are being scheduled on Dispatchers.IO and that these sometimes run concurrently. In the second stacktrace below it looks like two calls to TorManager#stop() are executing on threads DefaultDispatcher-worker-16 and DefaultDispatcher-worker-12, and presumably a third call to TorManager#stop() has also executed recently and unregistered the broadcast receiver.

```
2022-05-05 17:52:09.148 19454-21335/org.onionshare.android.nightly E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
    Process: org.onionshare.android.nightly, PID: 19454
    java.lang.IllegalArgumentException: Receiver not registered: org.onionshare.android.tor.TorManager$broadcastReceiver$1@556d3e3
        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1523)
        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1712)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:733)
        at org.onionshare.android.tor.TorManager.stop(TorManager.kt:142)
        at org.onionshare.android.ShareManager$stopSharing$2.invokeSuspend(ShareManager.kt:190)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2022-05-05 17:52:09.253 19454-21335/org.onionshare.android.nightly I/Process: Sending signal. PID: 19454 SIG: 9
```
```
2022-05-06 10:54:34.993 22016-21361/org.onionshare.android.nightly E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-16
    Process: org.onionshare.android.nightly, PID: 22016
    java.lang.IllegalArgumentException: Receiver not registered: org.onionshare.android.tor.TorManager$broadcastReceiver$1@9c18dd4
        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1523)
        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1712)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:733)
        at org.onionshare.android.tor.TorManager.stop(TorManager.kt:142)
        at org.onionshare.android.ShareManager$stopSharing$2.invokeSuspend(ShareManager.kt:190)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2022-05-06 10:54:34.993 22016-21313/org.onionshare.android.nightly E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-12
    Process: org.onionshare.android.nightly, PID: 22016
    java.lang.IllegalArgumentException: Receiver not registered: org.onionshare.android.tor.TorManager$broadcastReceiver$1@9c18dd4
        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1523)
        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1712)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:733)
        at org.onionshare.android.tor.TorManager.stop(TorManager.kt:142)
        at org.onionshare.android.ShareManager$stopSharing$2.invokeSuspend(ShareManager.kt:190)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2022-05-06 10:54:34.994 22016-21313/org.onionshare.android.nightly I/Process: Sending signal. PID: 22016 SIG: 9
```

**Comment by grote** [comment]
> Repeatedly tapping the button, with long or short pauses between taps, can lead to some strange behaviour, which occasionally includes crashes.

Maybe the simplest fix is to disable the button after clicked and only re-enable when the state changed?

Otherwise this probably relates to #5.
